version: "3.9"

services:
  tdlist:
    container_name: tdlist
    image: keshavkkumar/tdlist:1.0.0
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - tdlistdb
    volumes:
      - .:/var/www/html

  tdlistdb:
    container_name: tdlistdb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdataatodo:/var/lib/postgresql/data

volumes:
  pgdataatodo: {}